// Copy strings for Atlassian error codes surfaced on the sources
// strip.
//
// Each entry pairs a stable `atlassian.*` / `jira.*` / `confluence.*`
// error code from `dayseam_core::error_codes::ALL` with a short
// headline, a body that explains what the user is seeing and why it
// happened, and an optional `action` token the UI can branch on to
// render extra affordances.
//
// The two auth codes get `"reconnect"` because the only reasonable
// recovery is rotating the API token, and that's the flow
// `AddAtlassianSourceDialog` now owns. The walker "upstream_shape_
// changed" codes get `"none"` because there's nothing the user can
// usefully do — they're telemetry for Dayseam's own bug tracking.
// Rate-limit codes get `"none"` because DAY-82's HTTP client already
// honours `Retry-After` internally; the next sync picks up.
//
// Parity with Rust is guarded by `atlassianErrorCopy.test.ts`, which
// pulls the authoritative code list from `@dayseam/ipc-types`
// (regenerated by the `ts_types_generated` test) and asserts every
// entry lands here.

import type { AtlassianErrorCode } from "@dayseam/ipc-types";

export type AtlassianErrorAction = "reconnect" | "retry" | "none";

export interface AtlassianErrorCopy {
  title: string;
  body: string;
  action: AtlassianErrorAction;
}

export const atlassianErrorCopy: Record<
  AtlassianErrorCode,
  AtlassianErrorCopy
> = {
  "atlassian.auth.invalid_credentials": {
    title: "Atlassian credentials rejected",
    body: "The email or API token Dayseam stored was rejected by Atlassian. Reconnect this source with a fresh token to resume syncing.",
    action: "reconnect",
  },
  "atlassian.auth.missing_scope": {
    title: "Atlassian token is missing access",
    body: "The stored token works, but it doesn't have access to this workspace. Reconnect with a token created by an account that can read it.",
    action: "reconnect",
  },
  "atlassian.cloud.resource_not_found": {
    title: "Atlassian resource not found",
    body: "An issue, page, or comment Dayseam expected to read was moved, deleted, or put behind a permission we don't have. This one will be skipped on the next sync.",
    action: "none",
  },
  "atlassian.identity.malformed_account_id": {
    title: "Unexpected Atlassian account id",
    body: "Dayseam received an Atlassian account id in a shape it didn't recognise. If this keeps happening, file an issue with the workspace URL.",
    action: "none",
  },
  "atlassian.adf.unrenderable_node": {
    title: "Unsupported Atlassian content",
    body: "A Jira comment or Confluence page used a block Dayseam doesn't know how to render yet. The rest of the sync continues; the offending block appears as plain text.",
    action: "none",
  },
  "jira.walk.upstream_shape_changed": {
    title: "Unexpected response from Jira",
    body: "Dayseam received a payload shape it didn't recognise from this Jira instance. If this keeps happening, file an issue.",
    action: "none",
  },
  "jira.walk.rate_limited": {
    title: "Jira rate limit hit",
    body: "Jira asked Dayseam to slow down. The next sync will back off automatically — no action needed.",
    action: "none",
  },
  "confluence.walk.upstream_shape_changed": {
    title: "Unexpected response from Confluence",
    body: "Dayseam received a payload shape it didn't recognise from this Confluence instance. If this keeps happening, file an issue.",
    action: "none",
  },
  "confluence.walk.rate_limited": {
    title: "Confluence rate limit hit",
    body: "Confluence asked Dayseam to slow down. The next sync will back off automatically — no action needed.",
    action: "none",
  },
  "jira.upstream_5xx": {
    title: "Jira is having trouble",
    body: "Jira returned a server-side error (5xx). This is almost always a transient upstream outage — the next sync will retry automatically.",
    action: "none",
  },
  "jira.resource_gone": {
    title: "Jira resource permanently gone",
    body: "An issue or comment Dayseam was reading has been permanently deleted from Jira (410 Gone). It will be skipped on future syncs.",
    action: "none",
  },
  "confluence.upstream_5xx": {
    title: "Confluence is having trouble",
    body: "Confluence returned a server-side error (5xx). This is almost always a transient upstream outage — the next sync will retry automatically.",
    action: "none",
  },
  "confluence.resource_gone": {
    title: "Confluence resource permanently gone",
    body: "A page, comment, or attachment Dayseam was reading has been permanently deleted from Confluence (410 Gone). It will be skipped on future syncs.",
    action: "none",
  },
};
