// Copy strings for GitHub error codes surfaced on the sources strip.
//
// Each entry pairs a stable `github.*` error code from
// `dayseam_core::error_codes::ALL` with a short headline, a body that
// explains what the user is seeing and why it happened, and an
// optional `action` token the UI can branch on to render extra
// affordances.
//
// The two auth codes get `"reconnect"` because the only reasonable
// recovery is rotating the PAT, and that's the flow
// `AddGithubSourceDialog` owns (see the `reconnect` prop wired from
// `SourcesSidebar`). The walker "upstream_shape_changed" and
// "resource_*" codes get `"none"` because there's nothing the user
// can usefully do — they're telemetry for Dayseam's own bug tracking.
// Rate-limit codes get `"none"` because DAY-95's HTTP client already
// honours GitHub's `Retry-After` (and secondary `x-ratelimit-reset`)
// internally; the next sync picks up.
//
// Parity with Rust is guarded by `githubErrorCopy.test.ts`, which
// pulls the authoritative code list from `@dayseam/ipc-types`
// (regenerated by the `ts_types_generated` Rust test) and asserts
// every entry lands here.

import type { GithubErrorCode } from "@dayseam/ipc-types";

export type GithubErrorAction = "reconnect" | "retry" | "none";

export interface GithubErrorCopy {
  title: string;
  body: string;
  action: GithubErrorAction;
}

export const githubErrorCopy: Record<GithubErrorCode, GithubErrorCopy> = {
  "github.auth.invalid_credentials": {
    title: "GitHub credentials rejected",
    body: "The PAT Dayseam stored was rejected by GitHub. Reconnect this source with a fresh token to resume syncing.",
    action: "reconnect",
  },
  "github.auth.missing_scope": {
    title: "GitHub token is missing access",
    body: "The stored token works, but it's missing a scope Dayseam needs. Reconnect with a token that carries repo, read:org, and read:user scopes.",
    action: "reconnect",
  },
  "github.resource_not_found": {
    title: "GitHub resource not found",
    body: "A repository, issue, or pull request Dayseam expected to read was moved, deleted, or put behind a permission we don't have. This one will be skipped on the next sync.",
    action: "none",
  },
  "github.rate_limited": {
    title: "GitHub rate limit hit",
    body: "GitHub asked Dayseam to slow down. The next sync will back off automatically — no action needed.",
    action: "none",
  },
  "github.upstream_5xx": {
    title: "GitHub is having trouble",
    body: "GitHub returned a server-side error (5xx). This is almost always a transient upstream outage — the next sync will retry automatically.",
    action: "none",
  },
  "github.upstream_shape_changed": {
    title: "Unexpected response from GitHub",
    body: "Dayseam received a payload shape it didn't recognise from GitHub. If this keeps happening, file an issue with the API base URL.",
    action: "none",
  },
  "github.resource_gone": {
    title: "GitHub resource permanently gone",
    body: "A repository, issue, or pull request Dayseam was reading has been permanently deleted from GitHub (410 Gone). It will be skipped on future syncs.",
    action: "none",
  },
};
