// Copy strings for GitLab error codes surfaced on the sources strip.
//
// Each entry pairs a stable `gitlab.*` error code from
// `dayseam_core::error_codes::ALL` with a short headline, a body that
// explains what the user is seeing and why it happened, and an optional
// `action` token the UI can branch on to render extra affordances. The
// two auth codes get `"reconnect"` because the only reasonable recovery
// is rotating the PAT, and that's the flow `AddGitlabSourceDialog` now
// owns. The rest are informational — `rate_limited`, `upstream_5xx`,
// `url.*`, and `upstream_shape_changed` all resolve themselves or need
// a retry rather than a dialog.
//
// Parity with Rust is guarded by `gitlabErrorCopy.test.ts`, which pulls
// the authoritative code list from `@dayseam/ipc-types` (generated by
// the `ts_types_generated` test) and asserts every entry lands here.

import type { GitlabErrorCode } from "@dayseam/ipc-types";

export type GitlabErrorAction = "reconnect" | "retry" | "none";

export interface GitlabErrorCopy {
  title: string;
  body: string;
  action: GitlabErrorAction;
}

export const gitlabErrorCopy: Record<GitlabErrorCode, GitlabErrorCopy> = {
  "gitlab.auth.invalid_token": {
    title: "GitLab token rejected",
    body: "The personal access token Dayseam stored was rejected by GitLab. Reconnect this source with a fresh token to resume syncing.",
    action: "reconnect",
  },
  "gitlab.auth.missing_scope": {
    title: "GitLab token is missing a scope",
    body: "The stored token works, but it's missing the `read_api` scope Dayseam needs to read events. Reconnect with a token that includes `read_api`.",
    action: "reconnect",
  },
  "gitlab.url.dns": {
    title: "Can't reach GitLab",
    body: "The GitLab host didn't resolve. Check that you're online and that the base URL is spelled correctly, then retry.",
    action: "retry",
  },
  "gitlab.url.tls": {
    title: "TLS handshake failed",
    body: "Dayseam connected to the host but couldn't negotiate a secure connection. This usually means a proxy is intercepting TLS or the certificate is expired.",
    action: "retry",
  },
  "gitlab.rate_limited": {
    title: "GitLab rate limit hit",
    body: "GitLab asked Dayseam to slow down. The next sync will back off automatically — no action needed.",
    action: "none",
  },
  "gitlab.upstream_5xx": {
    title: "GitLab is having issues",
    body: "GitLab returned a server error. This usually resolves itself in a few minutes; Dayseam will retry on the next sync.",
    action: "retry",
  },
  "gitlab.upstream_shape_changed": {
    title: "Unexpected response from GitLab",
    body: "Dayseam received a payload shape it didn't recognise from this GitLab instance. If this keeps happening, file an issue with the instance version.",
    action: "none",
  },
  "gitlab.resource_not_found": {
    title: "GitLab resource not found",
    body: "GitLab returned 404 for a resource Dayseam expected to exist. The project, user, or event may have been deleted or moved — verify the source configuration and retry.",
    action: "retry",
  },
  "gitlab.resource_gone": {
    title: "GitLab resource permanently gone",
    body: "GitLab returned 410 for a resource that was permanently deleted. It will be skipped on future syncs.",
    action: "none",
  },
};
