// Copy strings for Outlook error codes surfaced on the sources strip
// and in `AddOutlookSourceDialog`.
//
// Each entry pairs a stable `outlook.*` or `ipc.outlook.*` error code
// from `dayseam_core::error_codes::ALL` with a short headline, a body
// that explains what the user is seeing and why it happened, and an
// optional `action` token the UI can branch on to render extra
// affordances.
//
// The two auth codes (`outlook.auth.*`) and `outlook.consent_required`
// get `"reconnect"` because the only real recovery is re-running the
// OAuth flow — possibly with the admin-consent route for
// `consent_required`. The walker telemetry codes
// (`outlook.resource_*`, `outlook.upstream_*`, `outlook.rate_limited`)
// get `"none"` because the next sync handles them automatically
// (rate-limit + 5xx back off via the shared HTTP client; `resource_*`
// is user-initiated data churn Dayseam just skips past).
//
// The `ipc.outlook.*` codes surface pre-network failures inside
// `outlook_validate_credentials` / `outlook_sources_add`:
//
//   - `session_not_found` / `session_not_ready` / `tenant_unresolved`:
//     the OAuth session that should carry the tokens isn't usable
//     yet (or was consumed); the dialog retries by restarting the
//     sign-in, so `"retry"` is the correct action.
//   - `keychain_write_failed`: OS keychain refused the write; the user
//     needs to unlock their login keychain and retry — `"retry"`
//     again because there's no external system to reconnect to.
//   - `source_already_exists`: the dialog-specific duplicate guard;
//     surfaced as `"none"` with copy that points at Settings rather
//     than re-running the sign-in.
//
// Parity with Rust is guarded by `outlookErrorCopy.test.ts`, which
// pulls the authoritative code list from `@dayseam/ipc-types`
// (regenerated by the `ts_types_generated` Rust test) and asserts
// every entry lands here.

import type { OutlookErrorCode } from "@dayseam/ipc-types";

export type OutlookErrorAction = "reconnect" | "retry" | "none";

export interface OutlookErrorCopy {
  title: string;
  body: string;
  action: OutlookErrorAction;
  /**
   * Optional URL the UI can link as a "what's this?" affordance.
   * Currently populated for `outlook.consent_required` to route the
   * end user to their tenant's admin-consent endpoint.
   */
  adminConsentUrl?: string;
}

/**
 * Azure AD admin-consent URL template. The dialog interpolates the
 * final `client_id` at render time when it's available; we keep a
 * generic fallback so the body copy stays useful even when the
 * dialog hasn't yet resolved the provider config.
 */
export const AZURE_ADMIN_CONSENT_URL =
  "https://login.microsoftonline.com/common/adminconsent";

export const outlookErrorCopy: Record<OutlookErrorCode, OutlookErrorCopy> = {
  "outlook.auth.invalid_credentials": {
    title: "Outlook sign-in rejected",
    body: "Microsoft refused the credentials Dayseam had stored for this account. Reconnect the source to sign in again and issue a fresh token.",
    action: "reconnect",
  },
  "outlook.auth.missing_scope": {
    title: "Outlook token is missing permissions",
    body: "The stored token is valid but is missing one of Calendars.Read, User.Read, or offline_access. Reconnect this source so Microsoft reissues a token with the full scope set.",
    action: "reconnect",
  },
  "outlook.consent_required": {
    title: "Your IT admin needs to approve Dayseam",
    body: "Your tenant requires admin-level consent before Dayseam can read calendars. Send this link to your IT admin and try again once they've approved: ",
    action: "reconnect",
    adminConsentUrl: AZURE_ADMIN_CONSENT_URL,
  },
  "outlook.resource_not_found": {
    title: "Outlook resource not found",
    body: "A calendar or event Dayseam expected to read was moved, deleted, or put behind a permission we don't have. This one will be skipped on the next sync.",
    action: "none",
  },
  "outlook.rate_limited": {
    title: "Outlook rate limit hit",
    body: "Microsoft Graph asked Dayseam to slow down. The next sync will back off automatically — no action needed.",
    action: "none",
  },
  "outlook.upstream_5xx": {
    title: "Microsoft Graph is having trouble",
    body: "Graph returned a server-side error (5xx). This is almost always a transient upstream outage — the next sync will retry automatically.",
    action: "none",
  },
  "outlook.upstream_shape_changed": {
    title: "Unexpected response from Microsoft Graph",
    body: "Dayseam received a payload shape it didn't recognise from Graph. If this keeps happening, file an issue with the API base URL.",
    action: "none",
  },
  "outlook.resource_gone": {
    title: "Outlook resource permanently gone",
    body: "A calendar or event Dayseam was reading has been permanently deleted from Microsoft Graph (410 Gone). It will be skipped on future syncs.",
    action: "none",
  },
  "ipc.outlook.session_not_found": {
    title: "Sign-in session expired",
    body: "The sign-in session Dayseam was tracking has already been consumed or timed out. Start the sign-in again to continue.",
    action: "retry",
  },
  "ipc.outlook.session_not_ready": {
    title: "Sign-in isn't finished yet",
    body: "Dayseam tried to validate the sign-in before Microsoft finished issuing tokens. Wait a moment, or start the sign-in again if the browser window never returned here.",
    action: "retry",
  },
  "ipc.outlook.keychain_write_failed": {
    title: "Couldn't save credentials to the keychain",
    body: "Dayseam signed in successfully but couldn't write the tokens to the OS keychain. Unlock your login keychain (or grant Dayseam access) and try again.",
    action: "retry",
  },
  "ipc.outlook.tenant_unresolved": {
    title: "Couldn't read tenant from the token",
    body: "Microsoft returned a token whose payload Dayseam couldn't parse for a tenant id. This is almost always a transient sign-in issue — try signing in again.",
    action: "retry",
  },
  "ipc.outlook.source_already_exists": {
    title: "This calendar is already connected",
    body: "Dayseam already has an Outlook source for this user in this tenant. Open Settings to manage the existing source rather than adding a second one.",
    action: "none",
  },
};
